---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: johnpapa/angular-cli
    tag: 'latest' 

inputs:
  - name: training-cf-ui   

run:
  path: training-cf-ui/ci/tasks/build-artifact.sh